package com.example.myfirstdaogeneraotor.model;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.example.myfirstdaogeneraotor.model.Employee;
import com.example.myfirstdaogeneraotor.model.Admin;

import com.example.myfirstdaogeneraotor.model.EmployeeDao;
import com.example.myfirstdaogeneraotor.model.AdminDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig employeeDaoConfig;
    private final DaoConfig adminDaoConfig;

    private final EmployeeDao employeeDao;
    private final AdminDao adminDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        employeeDaoConfig = daoConfigMap.get(EmployeeDao.class).clone();
        employeeDaoConfig.initIdentityScope(type);

        adminDaoConfig = daoConfigMap.get(AdminDao.class).clone();
        adminDaoConfig.initIdentityScope(type);

        employeeDao = new EmployeeDao(employeeDaoConfig, this);
        adminDao = new AdminDao(adminDaoConfig, this);

        registerDao(Employee.class, employeeDao);
        registerDao(Admin.class, adminDao);
    }
    
    public void clear() {
        employeeDaoConfig.getIdentityScope().clear();
        adminDaoConfig.getIdentityScope().clear();
    }

    public EmployeeDao getEmployeeDao() {
        return employeeDao;
    }

    public AdminDao getAdminDao() {
        return adminDao;
    }

}
